// enum for environment variables in configuration file .env
export enum XEnvVar {
    VITE_BACKEND_URL = 'VITE_BACKEND_URL',
    VITE_AUTH = 'VITE_AUTH',

    VITE_AUTH_OFF_USERNAME = 'VITE_AUTH_OFF_USERNAME',

    VITE_AUTH0_DOMAIN = 'VITE_AUTH0_DOMAIN',
    VITE_AUTH0_CLIENT_ID = 'VITE_AUTH0_CLIENT_ID',
    VITE_AUTH0_AUDIENCE = 'VITE_AUTH0_AUDIENCE',
    //VITE_AUTH0_SCOPE = 'VITE_AUTH0_SCOPE'

    VITE_MS_ENTRA_ID_TENANT_ID = 'VITE_MS_ENTRA_ID_TENANT_ID',
    VITE_MS_ENTRA_ID_CLIENT_ID = 'VITE_MS_ENTRA_ID_CLIENT_ID',
    VITE_MS_ENTRA_ID_BACKEND_SCOPE = 'VITE_MS_ENTRA_ID_BACKEND_SCOPE',

    VITE_LEGACY_OBJECT_LOADING = 'VITE_LEGACY_OBJECT_LOADING'
}

// enum for values of the environment variable VITE_AUTH
export enum XViteAuth {
    OFF = 'OFF',
    LOCAL = 'LOCAL',
    AUTH0 = 'AUTH0',
    MS_ENTRA_ID = 'MS_ENTRA_ID'
}
